<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_username</name>
   <tag></tag>
   <elementGuidId>01a4618e-0cf0-4087-b95f-4b19870f6aa6</elementGuidId>
   <imagePath>Screenshots/Targets/input_Username_username.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/input_Username_username.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='login']/div/div/div[2]/form/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt-username-broken</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'txt-username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt-username</value>
      <webElementGuid>b88e5366-a674-4fc9-bb39-293a7f2e428b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
